import React, { useState } from 'react';
import { ScrollView, View, Text, Image, StyleSheet, TouchableOpacity } from 'react-native';

export default function About() {
  const initialDescriptions = [
    "A wildfire is an uncontrolled and often rapidly spreading fire that occurs in natural landscapes, such as forests, grasslands, and shrublands. These fires are characterized by their ability to burn and spread quickly, often driven by factors like dry conditions, wind, and the presence of flammable vegetation. Wildfires can vary in size and intensity, ranging from small, localized blazes to massive infernos that cover vast areas. They can be ignited by natural causes like lightning strikes or human activities, such as campfires, discarded cigarettes, or arson. Wildfires have the potential to cause significant damage to the environment, wildlife habitats, property, and can pose a threat to human lives if not properly managed and controlled.",
    "Wildfires primarily occur due to a combination of natural and human factors. Natural factors include lightning strikes, volcanic eruptions, and spontaneous combustion of dry vegetation. However, human activities play a significant role in igniting wildfires, such as campfires left unattended, discarded cigarette butts, power lines sparking, and arson. Once ignited, wildfires spread quickly, driven by factors like dry weather, strong winds, and the presence of flammable vegetation. Extended periods of drought and climate change can exacerbate wildfire risk by creating dry conditions that make it easier for fires to ignite and spread. Additionally, urban expansion into wildland areas increases the likelihood of human-caused ignitions, making wildfire prevention and management crucial for protecting both people and the environment.",
    "Wildfires can cause significant harm in several ways. Firstly, they pose a direct threat to human lives and property, leading to injuries, fatalities, and the destruction of homes and infrastructure. Secondly, wildfires harm the environment by destroying natural habitats, killing wildlife, and disruptingmecosystems. The loss of vegetation and soil erosion can lead to long-term environmental damage, impactingmwater quality and increasing the risk of mudslides and flooding. Additionally, the smoke and air pollutionmgenerated by wildfires can have adverse health effects on people, particularly those with respiratory,issues, and can contribute to poor air quality over large regions. Overall, wildfires can have devastating social, economic, and environmental consequences.",
  ];

  const [showFullDescriptions, setShowFullDescriptions] = useState([false, false, false]);

  const toggleDescription = (index) => {
    const updatedDescriptions = [...showFullDescriptions];
    updatedDescriptions[index] = !updatedDescriptions[index];
    setShowFullDescriptions(updatedDescriptions);
  };

  return (
    <ScrollView contentContainerStyle={styles.container}>
      <View style={styles.sectionContainer}>
        <Image source={require("../../assets/img/wf1.jpg")} style={styles.coverImage} />
        <Text style={styles.sectionTitle}>About Wildfire?</Text>
        <Text style={styles.description}>
          {showFullDescriptions[0]
            ? `${initialDescriptions[0]}`
            : `A wildfire is an uncontrolled and often rapidly spreading fire that occurs in natural landscapes, such as forests, grasslands, and shrublands.`}
        </Text>
        {initialDescriptions[0].split(' ').length > 10 && (
          <TouchableOpacity onPress={() => toggleDescription(0)}>
            <Text style={styles.showMoreButton}>
              {showFullDescriptions[0] ?  'Show Less' : 'Show More'}
            </Text>
          </TouchableOpacity>
        )}
      </View>

      <View style={styles.sectionContainer}>
        <Image source={require("../../assets/img/wf2.jpg")} style={styles.coverImage} />
        <Text style={styles.sectionTitle}>What is the reason of Wildfire?</Text>
        <Text style={styles.description}>
          {showFullDescriptions[1]
            ? `${initialDescriptions[1]}`
            : `Wildfires primarily occur due to a combination of natural and human factors.`}
        </Text>
        {initialDescriptions[1].split(' ').length > 10 && (
          <TouchableOpacity onPress={() => toggleDescription(1)}>
            <Text style={styles.showMoreButton}>
              {showFullDescriptions[1] ?  'Show Less' : 'Show More'}
            </Text>
          </TouchableOpacity>
        )}
      </View>

      <View style={styles.sectionContainer}>
        <Image source={require("../../assets/img/wf3.jpg")} style={styles.coverImage} />
        <Text style={styles.sectionTitle}>What is Wildfire?</Text>
        <Text style={styles.description}>
          {showFullDescriptions[2]
            ? `${initialDescriptions[2]}`
            : `Wildfires can cause significant harm in several ways.`}
        </Text>
        {initialDescriptions[2].split(' ').length > 10 && (
          <TouchableOpacity onPress={() => toggleDescription(2)}>
            <Text style={styles.showMoreButton}>
              {showFullDescriptions[2] ? 'Show Less' : 'Show More'}
            </Text>
          </TouchableOpacity>
        )}
      </View>

      {/* Add more sections for additional images and titles */}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: '#fff',
  },
  sectionContainer: {
    marginVertical: 20,
    paddingHorizontal: 20,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#333',
  },
  subtitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#333',
  },
  coverImage: {
    width: '100%',
    height: 200,
    resizeMode: 'cover',
    borderRadius: 10,
  },
  description: {
    fontSize: 16,
    lineHeight: 24,
    color: '#555',
    textAlign: 'justify',
  },
  showMoreButton: {
    width: '40%',
    marginTop: 10,
    color: '#333', // Text color
    fontSize: 14, // Smaller font size
    fontWeight: 'bold', // Bold text for better visibility
    backgroundColor: '#f0f0f0', // Background color for the button
    paddingVertical: 6, // Vertical padding for the button
    paddingHorizontal: 12, // Horizontal padding for the button
    borderRadius: 15, // Border radius for rounded corners
    textAlign: 'center',
    overflow: 'hidden',
  },
  
  
});
